# Generated by Django 6.0.3 on 2026-04-21 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalinstance',
            name='target_type',
            field=models.CharField(choices=[('procurement_request', 'Procurement Request'), ('finance_invoice', 'Finance Invoice'), ('payment_request', 'Payment Request')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalworkflowtemplate',
            name='module_key',
            field=models.CharField(choices=[('procurement_request', 'Procurement Request'), ('finance_invoice', 'Finance Invoice'), ('payment_request', 'Payment Request')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ApprovalHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('registered', 'Registered'), ('submitted', 'Submitted'), ('comment', 'Comment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reverted', 'Reverted'), ('step_advanced', 'Step Advanced'), ('completed', 'Completed')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_history_entries', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='enterprise.approvalinstance')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='enterprise.approvalworkflowstep')),
            ],
            options={
                'db_table': 'enterprise_approval_history_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instance', '-created_at'], name='enterprise__instanc_42aba4_idx'), models.Index(fields=['event_type', '-created_at'], name='enterprise__event_t_de78a3_idx')],
            },
        ),
    ]
