# Generated by Django 6.0.3 on 2026-04-22 05:33

import django.db.models.deletion
import enterprise.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_alter_approvalinstance_target_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('procurement_request', 'Procurement Request'), ('goods_receipt', 'Goods Receipt'), ('finance_invoice', 'Finance Invoice'), ('payment_request', 'Payment Request')], db_index=True, max_length=40)),
                ('target_id', models.UUIDField(db_index=True)),
                ('file', models.FileField(upload_to=enterprise.models.enterprise_attachment_path)),
                ('attachment_type', models.CharField(default='Supporting Document', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='enterprise.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_enterprise_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_attachment',
                'ordering': ['uploaded_at'],
                'indexes': [models.Index(fields=['organization', 'target_type', 'target_id'], name='enterprise__organiz_2bbabc_idx')],
            },
        ),
    ]
