# Generated by Django 6.0.3 on 2026-04-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_enterpriseattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='currency_code',
            field=models.CharField(default='TZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='Africa/Dar_es_Salaam', max_length=80),
        ),
    ]
