# Generated by Django 4.2.13 on 2026-03-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=20)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted Confirmation'), ('REQUEST_APPROVED', 'Request Approval Notification'), ('REQUEST_REJECTED', 'Request Rejection Notification'), ('PAYMENT_PROCESSED', 'Payment Processed Confirmation'), ('REMINDER_PAYMENT', 'Payment Reminder'), ('EVENT_INVITATION', 'Event Invitation'), ('EVENT_REMINDER', 'Event Reminder'), ('APPROVAL_REQUIRED', 'Approval Required Alert'), ('SYSTEM_ALERT', 'System Alert'), ('STATUS_CHANGED', 'Status Changed Notification')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('plain_text_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_template',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_PAID', 'Request Paid'), ('EVENT_CREATED', 'Event Created'), ('DAILY_SCHEDULE', 'Daily Schedule'), ('WEEKLY_SCHEDULE', 'Weekly Schedule'), ('THRESHOLD_REACHED', 'Budget Threshold Reached'), ('OVERDUE_PAYMENT', 'Overdue Payment')], max_length=50)),
                ('action', models.CharField(choices=[('SEND_EMAIL', 'Send Email'), ('SEND_SMS', 'Send SMS'), ('UPDATE_STATUS', 'Update Status'), ('ASSIGN_REVIEWER', 'Assign Reviewer'), ('CREATE_REMINDER', 'Create Reminder'), ('GENERATE_REPORT', 'Generate Report'), ('ESCALATE', 'Escalate'), ('ARCHIVE', 'Archive')], max_length=50)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('target_users', models.JSONField(blank=True, default=list)),
                ('email_template', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_action',
                'ordering': ['trigger', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_object_type', models.CharField(max_length=50)),
                ('trigger_object_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workflowaction')),
            ],
            options={
                'db_table': 'workflow_execution',
                'ordering': ['-created_at'],
            },
        ),
    ]
