# Generated by Django 4.2.13 on 2026-03-13 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_notificationreceipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(blank=True, db_index=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permission',
                'ordering': ['module', 'key'],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role_definition',
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('admin', 'Administrator'), ('staff', 'Staff'), ('finance_officer', 'Finance Officer'), ('auditor', 'Auditor / Viewer'), ('it_admin', 'IT / System Admin')], default='staff', help_text='User role for RBAC', max_length=20),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.roledefinition')),
            ],
            options={
                'db_table': 'role_permission',
                'indexes': [models.Index(fields=['role', 'permission'], name='role_permis_role_id_f4f546_idx')],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
