# Generated by Django 6.0.3 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(
                choices=[
                    ('REQUEST_SUBMITTED', 'Request Submitted Confirmation'),
                    ('REQUEST_APPROVED', 'Request Approval Notification'),
                    ('REQUEST_REJECTED', 'Request Rejection Notification'),
                    ('PAYMENT_PROCESSED', 'Payment Processed Confirmation'),
                    ('REMINDER_PAYMENT', 'Payment Reminder'),
                    ('EVENT_INVITATION', 'Event Invitation'),
                    ('EVENT_REMINDER', 'Event Reminder'),
                    ('APPROVAL_REQUIRED', 'Approval Required Alert'),
                    ('SYSTEM_ALERT', 'System Alert'),
                    ('STATUS_CHANGED', 'Status Changed Notification'),
                    ('INVITATION_STATUS_UPDATE', 'Invitation Status Update'),
                    ('REMINDER_ALERT', 'Reminder Alert'),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
