# Generated by Django 6.0.3 on 2026-03-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_restrict_audit_log_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
