# Generated by Django 6.0.3 on 2026-03-17 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_profile_change_password_permission'),
        ('invitations', '0004_alter_invitation_status'),
        ('requests', '0004_alter_request_status_alter_requesthistory_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('status_change', 'Status Change'), ('internal_note', 'Internal Note'), ('director_comment', 'Director Comment'), ('admin_note', 'Admin Note'), ('approval_action', 'Approval Action'), ('revert_action', 'Revert Action'), ('payment_action', 'Payment Action'), ('system_event', 'System Event')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('old_status', models.CharField(blank=True, max_length=60)),
                ('new_status', models.CharField(blank=True, max_length=60)),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='invitations.invitation')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='requests.request')),
            ],
            options={
                'db_table': 'record_timeline_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', '-created_at'], name='record_time_request_4bca28_idx'), models.Index(fields=['invitation', '-created_at'], name='record_time_invitat_0ed8b5_idx'), models.Index(fields=['entry_type', '-created_at'], name='record_time_entry_t_86526f_idx'), models.Index(fields=['is_internal', '-created_at'], name='record_time_is_inte_5d157c_idx')],
            },
        ),
    ]
