# Generated by Codex on 2026-03-17

import re
from django.db import migrations


REQUEST_TITLE_MAP = {
    "created": ("system_event", "Request created", False),
    "updated": ("system_event", "Request updated", False),
    "submitted": ("status_change", "Request submitted", False),
    "moved_to_review": ("status_change", "Request moved to under review", False),
    "approved": ("approval_action", "Request approved", False),
    "rejected": ("approval_action", "Request rejected", False),
    "partially_paid": ("payment_action", "Partial payment recorded", False),
    "paid": ("payment_action", "Payment completed", False),
    "cancelled": ("status_change", "Request cancelled", True),
    "restored": ("status_change", "Request restored", True),
    "reversed": ("revert_action", "Decision reverted", False),
    "document_uploaded": ("system_event", "Document uploaded", False),
}


def _split_comment(description: str) -> tuple[str, str]:
    for marker in (" Comment: ", " Reason: ", " Notes: "):
        if marker in description:
            body, comment = description.split(marker, 1)
            return body.strip(), comment.strip()
    return description.strip(), ""


def _extract_transition(description: str) -> tuple[str, str]:
    match = re.search(r"\(([^()]+?) -> ([^()]+?)\)", description)
    if not match:
        return "", ""
    return match.group(1).strip(), match.group(2).strip()


def _invitation_title_and_type(description: str) -> tuple[str, str]:
    lowered = description.lower()
    if "accepted invitation" in lowered:
        return "approval_action", "Invitation accepted"
    if "declined invitation" in lowered:
        return "approval_action", "Invitation declined"
    if "confirmed attendance" in lowered:
        return "approval_action", "Attendance confirmed"
    if "reverted invitation decision" in lowered:
        return "revert_action", "Decision reverted"
    if "updated invitation status" in lowered:
        return "status_change", "Invitation status updated"
    if "marked invitation" in lowered and "completed" in lowered:
        return "status_change", "Invitation marked completed"
    return "system_event", "Invitation created"


def backfill_record_timeline_entries(apps, schema_editor):
    RecordTimelineEntry = apps.get_model("core", "RecordTimelineEntry")
    RequestHistory = apps.get_model("requests", "RequestHistory")
    Request = apps.get_model("requests", "Request")
    AuditLog = apps.get_model("core", "AuditLog")
    Invitation = apps.get_model("invitations", "Invitation")

    valid_request_ids = set(Request.objects.values_list("id", flat=True))
    valid_invitation_ids = {str(pk) for pk in Invitation.objects.values_list("id", flat=True)}

    request_entries = []
    for history in RequestHistory.objects.all().iterator():
        if history.request_id not in valid_request_ids:
            continue
        entry_type, title, is_internal = REQUEST_TITLE_MAP.get(history.action, ("system_event", "Request updated", False))
        request_entries.append(
            RecordTimelineEntry(
                request_id=history.request_id,
                actor_id=history.performed_by_id,
                entry_type=entry_type,
                title=title,
                body=history.comment or "",
                old_status=history.from_status or "",
                new_status=history.to_status or "",
                is_internal=is_internal,
                created_at=history.created_at,
            )
        )

    if request_entries:
        RecordTimelineEntry.objects.bulk_create(request_entries, batch_size=500)

    invitation_entries = []
    for audit in AuditLog.objects.filter(content_type="Invitation").iterator():
        if audit.object_id not in valid_invitation_ids:
            continue
        description, comment = _split_comment(audit.description or "")
        entry_type, title = _invitation_title_and_type(description)
        old_status, new_status = _extract_transition(description)
        invitation_entries.append(
            RecordTimelineEntry(
                invitation_id=audit.object_id,
                actor_id=audit.user_id,
                entry_type=entry_type,
                title=title,
                body=comment,
                old_status=old_status,
                new_status=new_status,
                is_internal=False,
                created_at=audit.created_at,
            )
        )

    if invitation_entries:
        RecordTimelineEntry.objects.bulk_create(invitation_entries, batch_size=500)


def reverse_backfill(apps, schema_editor):
    RecordTimelineEntry = apps.get_model("core", "RecordTimelineEntry")
    RecordTimelineEntry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_recordtimelineentry"),
    ]

    operations = [
        migrations.RunPython(backfill_record_timeline_entries, reverse_backfill),
    ]
