# Generated by Django 6.0.3 on 2026-03-04 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('smtp_server', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('sms_api_key', models.CharField(blank=True, max_length=500)),
                ('sms_provider', models.CharField(blank=True, choices=[('twilio', 'Twilio'), ('nexmo', 'Nexmo'), ('custom', 'Custom')], max_length=100)),
                ('auto_backup_enabled', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=50)),
                ('backup_retention_days', models.IntegerField(default=30)),
                ('site_name', models.CharField(default='CTRMS', max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_email', models.EmailField(max_length=254)),
                ('support_email', models.EmailField(max_length=254)),
                ('enable_encryption', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
