# Generated by Django 6.0.3 on 2026-03-06 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(default='Chakou Trust', max_length=255)),
                ('organization_slug', models.SlugField(default='chakou-trust', unique=True)),
                ('organization_email', models.EmailField(max_length=254)),
                ('organization_phone', models.CharField(blank=True, max_length=20)),
                ('organization_address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo for navbar (recommended: 200x50px, PNG with transparent background)', null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon for browser tab (recommended: 32x32px)', null=True, upload_to='logos/')),
                ('banner_image', models.ImageField(blank=True, help_text='Homepage banner image (recommended: 1920x400px)', null=True, upload_to='banners/')),
                ('primary_color', models.CharField(default='#667eea', help_text='Primary brand color (hex format)', max_length=7)),
                ('secondary_color', models.CharField(default='#764ba2', help_text='Secondary brand color (hex format)', max_length=7)),
                ('accent_color', models.CharField(default='#f093fb', help_text='Accent color (hex format)', max_length=7)),
                ('website_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('about_us', models.TextField(blank=True)),
                ('mission_statement', models.TextField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=500)),
                ('show_social_links', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
                'db_table': 'organization_settings',
            },
        ),
    ]
