# Generated by Django 4.2.13 on 2026-03-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_organizationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='event_reminder_1_day_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='event_reminder_3_days_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
