# Generated by Django 6.0.3 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_systemsettings_event_reminder_1_day_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sender_name',
            field=models.CharField(default='CTRMS', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
