# Generated by Django 6.0.3 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_systemsettings_email_runtime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='organization_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='organization_slug',
            field=models.SlugField(default='organization', unique=True),
        ),
    ]
