from django.urls import path

from .api import (
    approve_request_ajax,
    create_event_ajax,
    get_activity_logs_data,
    get_dashboard_overview,
    get_dashboard_stats,
    get_notifications_data,
    mark_notification_read_api,
    public_branding_data,
    search_api,
    get_documents_data,
    get_requests_data,
    get_system_settings_data,
    get_user_management_data,
    get_rbac_overview_api,
    send_test_email_api,
    mark_as_paid_ajax,
    reject_request_ajax,
    change_own_password_api,
    create_user_api,
    deactivate_user_api,
    reactivate_user_api,
    reset_user_password_api,
    update_user_api,
    update_role_permissions_api,
    upload_organization_assets_api,
    session_login,
    session_logout,
    session_status,
    submit_request_form,
)
from .exports import (
    export_analytics_report_csv,
    export_financial_report_csv,
    export_requests_csv,
    export_requests_excel,
    export_requests_pdf,
)

urlpatterns = [
    path('api/submit-request/', submit_request_form, name='submit_request_form'),
    path('api/approve-request/', approve_request_ajax, name='approve_request_ajax'),
    path('api/reject-request/', reject_request_ajax, name='reject_request_ajax'),
    path('api/mark-paid/', mark_as_paid_ajax, name='mark_paid_ajax'),
    path('api/requests-data/', get_requests_data, name='get_requests_data'),
    path('api/dashboard-stats/', get_dashboard_stats, name='get_dashboard_stats'),
    path('api/create-event/', create_event_ajax, name='create_event_ajax'),
    path('api/session/', session_status, name='api_session_status'),
    path('api/public-branding/', public_branding_data, name='api_public_branding'),
    path('api/session/login/', session_login, name='api_session_login'),
    path('api/session/logout/', session_logout, name='api_session_logout'),
    path('api/session/change-password/', change_own_password_api, name='api_session_change_password'),
    path('api/dashboard-overview/', get_dashboard_overview, name='api_dashboard_overview'),
    path('api/documents-data/', get_documents_data, name='api_documents_data'),
    path('api/activity-logs-data/', get_activity_logs_data, name='api_activity_logs_data'),
    path('api/notifications-data/', get_notifications_data, name='api_notifications_data'),
    path('api/notifications/<uuid:receipt_id>/read/', mark_notification_read_api, name='api_notifications_read'),
    path('api/search/', search_api, name='api_search'),
    path('api/user-management-data/', get_user_management_data, name='api_user_management_data'),
    path('api/system-settings-data/', get_system_settings_data, name='api_system_settings_data'),
    path('api/system-settings-test-email/', send_test_email_api, name='api_system_settings_test_email'),
    path('api/system-settings-assets/', upload_organization_assets_api, name='api_system_settings_assets'),
    path('api/users/', create_user_api, name='api_users_create'),
    path('api/users/<uuid:user_id>/', update_user_api, name='api_users_update'),
    path('api/users/<uuid:user_id>/deactivate/', deactivate_user_api, name='api_users_deactivate'),
    path('api/users/<uuid:user_id>/reactivate/', reactivate_user_api, name='api_users_reactivate'),
    path('api/users/<uuid:user_id>/reset-password/', reset_user_password_api, name='api_users_reset_password'),
    path('api/rbac/', get_rbac_overview_api, name='api_rbac_overview'),
    path('api/rbac/roles/<str:role_key>/', update_role_permissions_api, name='api_rbac_update_role'),

    path('export/requests-csv/', export_requests_csv, name='export_requests_csv'),
    path('export/requests-excel/', export_requests_excel, name='export_requests_excel'),
    path('export/requests-pdf/', export_requests_pdf, name='export_requests_pdf'),
    path('export/financial-report-csv/', export_financial_report_csv, name='export_financial_csv'),
    path('export/analytics-report-csv/', export_analytics_report_csv, name='export_analytics_csv'),
]
