# Generated by Django 6.0.3 on 2026-03-04 13:24

import django.core.validators
import django.db.models.deletion
import requests.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(db_index=True, help_text='Auto-generated unique request ID', max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(max_length=20)),
                ('applicant_id', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('medical', 'Medical Support'), ('construction', 'Construction Aid'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid/Completed')], db_index=True, default='pending', max_length=50)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='e.g., Bank Transfer, Check, Cash', max_length=100)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(help_text='Supported formats: PDF, JPG, PNG', upload_to=requests.models.request_document_path)),
                ('document_type', models.CharField(help_text='e.g., Invoice, Medical Report, ID Card', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='requests.request')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Document',
                'verbose_name_plural': 'Request Documents',
                'db_table': 'request_document',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', '-created_at'], name='request_status_5a2e32_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['category', 'status'], name='request_categor_e48f90_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['applicant_email'], name='request_applica_ddfd29_idx'),
        ),
    ]
