# Generated by Django 4.2.13 on 2026-03-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='applicant_organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='applicant_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='applicant_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='number_of_beneficiaries',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
