# Generated by Django 4.2.13 on 2026-03-13 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0002_request_applicant_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid/Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('moved_to_review', 'Moved to review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('restored', 'Restored'), ('reversed', 'Reversed'), ('document_uploaded', 'Document uploaded')], db_index=True, max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_history_entries', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='requests.request')),
            ],
            options={
                'db_table': 'request_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', '-created_at'], name='request_his_request_e83f91_idx'), models.Index(fields=['action', '-created_at'], name='request_his_action_f3bd63_idx')],
            },
        ),
    ]
