# Generated by Django 6.0.3 on 2026-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_created_by_alter_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid / Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('moved_to_review', 'Moved to review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('restored', 'Restored'), ('reversed', 'Reversed'), ('document_uploaded', 'Document uploaded')], db_index=True, max_length=40),
        ),
    ]
