# Generated by Django 6.0.3 on 2026-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0004_alter_request_status_alter_requesthistory_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="category",
            field=models.CharField(
                choices=[
                    ("tuition", "Tuition"),
                    ("medical", "Medical Support"),
                    ("construction", "Construction Aid"),
                    ("event_sponsorship", "Event Sponsorship"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
