# Generated by Django 6.0.3 on 2026-04-23 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_request_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='finance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='finance_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='finance_processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_processed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='workflow_route',
            field=models.CharField(choices=[('normal_funded', 'Normal Funded Request'), ('inventory', 'Inventory Request')], db_index=True, default='normal_funded', max_length=30),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('medical', 'Medical Support'), ('construction', 'Construction Aid'), ('event_sponsorship', 'Event Sponsorship'), ('welfare', 'Welfare Support'), ('operational_support', 'Operational Support'), ('reimbursement', 'Reimbursement'), ('petty_cash', 'Petty Cash / Advance'), ('finance_request', 'Finance Request'), ('inventory_request', 'Inventory Request'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Submitted'), ('under_review', 'Director Review'), ('director_approved', 'Director Approved'), ('director_rejected', 'Director Rejected'), ('needs_clarification', 'Needs Clarification'), ('finance_processing', 'Finance Processing'), ('finance_query', 'Finance Query'), ('pending_payment', 'Pending Payment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid / Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('moved_to_review', 'Moved to review'), ('director_approved', 'Director approved'), ('director_rejected', 'Director rejected'), ('clarification_requested', 'Clarification requested'), ('finance_processing', 'Finance processing started'), ('finance_query', 'Finance query raised'), ('pending_payment', 'Pending payment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('restored', 'Restored'), ('reversed', 'Reversed'), ('document_uploaded', 'Document uploaded')], db_index=True, max_length=40),
        ),
    ]
