# Generated by Django 6.0.3 on 2026-03-04 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inviting_organization', models.CharField(help_text='Name of the organization issuing the invitation', max_length=255)),
                ('event_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('event_duration_hours', models.IntegerField(default=2, help_text='Duration of the event in hours')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('confirmed_attendance', 'Confirmed Attendance'), ('completed', 'Completed')], db_index=True, default='pending_review', max_length=50)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('rsvp_required', models.BooleanField(default=True)),
                ('expected_attendees', models.IntegerField(blank=True, null=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('reminder_3_days_sent', models.BooleanField(default=False)),
                ('reminder_1_day_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'invitation',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='InvitationReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('3_days', '3 Days Before'), ('1_day', '1 Day Before')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('dashboard', 'Dashboard Alert'), ('sms', 'SMS')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Invitation Reminder',
                'verbose_name_plural': 'Invitation Reminders',
                'db_table': 'invitation_reminder',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['status', 'event_date'], name='invitation_status_c2900f_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['event_date'], name='invitation_event_d_abdfef_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['-created_at'], name='invitation_created_b777a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invitationreminder',
            unique_together={('invitation', 'reminder_type', 'channel')},
        ),
    ]
