# Generated by Django 4.2.13 on 2026-03-09 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invitations.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=invitations.models.invitation_attachment_path)),
                ('attachment_type', models.CharField(default='Supporting Document', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='invitations.invitation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invitation_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitation_attachment',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
