# Generated by Django 6.0.3 on 2026-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_invitation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('confirmed_attendance', 'Confirmed Attendance'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='pending_review', max_length=50),
        ),
    ]
