from django.urls import path

from .views import (
    approval_inbox_api,
    branch_api,
    branch_detail_api,
    department_api,
    department_detail_api,
    enterprise_attachment_download_api,
    enterprise_overview_api,
    finance_workspace_api,
    finance_invoice_approve_api,
    finance_invoice_attachment_upload_api,
    finance_invoice_comment_api,
    finance_invoice_create_payment_request_api,
    finance_invoice_post_api,
    finance_invoice_revert_api,
    goods_receipt_attachment_upload_api,
    inventory_workspace_api,
    organization_workspace_api,
    payment_request_attachment_upload_api,
    payment_request_comment_api,
    payment_request_approve_api,
    payment_request_mark_paid_api,
    payment_request_reject_api,
    payment_request_revert_api,
    procurement_request_attachment_upload_api,
    procurement_request_approve_api,
    procurement_request_comment_api,
    procurement_request_convert_api,
    procurement_request_create_api,
    procurement_request_reject_api,
    procurement_request_revert_api,
    procurement_request_submit_api,
    procurement_request_update_api,
    procurement_workspace_api,
    purchase_order_issue_api,
    purchase_order_receive_api,
)


urlpatterns = [
    path("api/enterprise/overview/", enterprise_overview_api, name="api_enterprise_overview"),
    path("api/enterprise/approvals/inbox/", approval_inbox_api, name="api_enterprise_approval_inbox"),
    path("api/enterprise/procurement/", procurement_workspace_api, name="api_enterprise_procurement"),
    path("api/enterprise/procurement/requests/", procurement_request_create_api, name="api_enterprise_procurement_request_create"),
    path("api/enterprise/procurement/requests/<uuid:request_id>/", procurement_request_update_api, name="api_enterprise_procurement_request_update"),
    path("api/enterprise/procurement/requests/<uuid:request_id>/submit/", procurement_request_submit_api, name="api_enterprise_procurement_request_submit"),
    path("api/enterprise/procurement/requests/<uuid:request_id>/approve/", procurement_request_approve_api, name="api_enterprise_procurement_request_approve"),
    path("api/enterprise/procurement/requests/<uuid:request_id>/reject/", procurement_request_reject_api, name="api_enterprise_procurement_request_reject"),
    path("api/enterprise/procurement/requests/<uuid:request_id>/revert/", procurement_request_revert_api, name="api_enterprise_procurement_request_revert"),
    path("api/enterprise/procurement/requests/<uuid:request_id>/comment/", procurement_request_comment_api, name="api_enterprise_procurement_request_comment"),
    path("api/enterprise/procurement/requests/<uuid:request_id>/attachments/", procurement_request_attachment_upload_api, name="api_enterprise_procurement_request_attachment_upload"),
    path("api/enterprise/procurement/requests/<uuid:request_id>/convert/", procurement_request_convert_api, name="api_enterprise_procurement_request_convert"),
    path("api/enterprise/purchase-orders/<uuid:purchase_order_id>/issue/", purchase_order_issue_api, name="api_enterprise_purchase_order_issue"),
    path("api/enterprise/purchase-orders/<uuid:purchase_order_id>/receive/", purchase_order_receive_api, name="api_enterprise_purchase_order_receive"),
    path("api/enterprise/inventory/", inventory_workspace_api, name="api_enterprise_inventory"),
    path("api/enterprise/goods-receipts/<uuid:receipt_id>/attachments/", goods_receipt_attachment_upload_api, name="api_enterprise_goods_receipt_attachment_upload"),
    path("api/enterprise/finance/", finance_workspace_api, name="api_enterprise_finance"),
    path("api/enterprise/invoices/<uuid:invoice_id>/post/", finance_invoice_post_api, name="api_enterprise_invoice_post"),
    path("api/enterprise/invoices/<uuid:invoice_id>/approve/", finance_invoice_approve_api, name="api_enterprise_invoice_approve"),
    path("api/enterprise/invoices/<uuid:invoice_id>/revert/", finance_invoice_revert_api, name="api_enterprise_invoice_revert"),
    path("api/enterprise/invoices/<uuid:invoice_id>/comment/", finance_invoice_comment_api, name="api_enterprise_invoice_comment"),
    path("api/enterprise/invoices/<uuid:invoice_id>/attachments/", finance_invoice_attachment_upload_api, name="api_enterprise_invoice_attachment_upload"),
    path("api/enterprise/invoices/<uuid:invoice_id>/create-payment-request/", finance_invoice_create_payment_request_api, name="api_enterprise_invoice_create_payment_request"),
    path("api/enterprise/payment-requests/<uuid:payment_request_id>/approve/", payment_request_approve_api, name="api_enterprise_payment_request_approve"),
    path("api/enterprise/payment-requests/<uuid:payment_request_id>/reject/", payment_request_reject_api, name="api_enterprise_payment_request_reject"),
    path("api/enterprise/payment-requests/<uuid:payment_request_id>/revert/", payment_request_revert_api, name="api_enterprise_payment_request_revert"),
    path("api/enterprise/payment-requests/<uuid:payment_request_id>/comment/", payment_request_comment_api, name="api_enterprise_payment_request_comment"),
    path("api/enterprise/payment-requests/<uuid:payment_request_id>/attachments/", payment_request_attachment_upload_api, name="api_enterprise_payment_request_attachment_upload"),
    path("api/enterprise/payment-requests/<uuid:payment_request_id>/mark-paid/", payment_request_mark_paid_api, name="api_enterprise_payment_request_mark_paid"),
    path("api/enterprise/attachments/<uuid:attachment_id>/download/", enterprise_attachment_download_api, name="api_enterprise_attachment_download"),
    path("api/enterprise/organization/", organization_workspace_api, name="api_enterprise_organization"),
    path("api/enterprise/departments/", department_api, name="api_enterprise_department_create"),
    path("api/enterprise/departments/<uuid:dept_id>/", department_detail_api, name="api_enterprise_department_detail"),
    path("api/enterprise/branches/", branch_api, name="api_enterprise_branch_create"),
    path("api/enterprise/branches/<uuid:branch_id>/", branch_detail_api, name="api_enterprise_branch_detail"),
]
